# 🖼️ Мультимодальная модель с автоопределением model_type
# LLaVA-style: изображение + текст -> текст

# === ОСНОВНЫЕ ПАРАМЕТРЫ ===
model_name_or_path: "HuggingFaceH4/zephyr-7b-beta"  # Современная модель с safetensors поддержкой

# Указание модальностей - автоматически определит model_type: multimodal
modalities:
  input: ["image", "text"]
  output: ["text"]

# === VISION ENCODER ===
# Когда используются изображения, нужно указать энкодер
encoders:
  image:
    model: "openai/clip-vit-large-patch14"
    freeze: true

# === ПРОЕКЦИЯ ===
projection:
  type: "mlp"
  hidden_size: 1024
  num_layers: 2
  dropout: 0.1

# === ДАТАСЕТ ===
# Требуется конвертированный LLaVA датасет
dataset: ["hf_multimodal_dataset"]  # Используем стандартный HuggingFace датасет
conversation_field: "conversations"  # Наш датасет использует "conversations"

# === ПАРАМЕТРЫ ОБУЧЕНИЯ ===
output_dir: "./output/multimodal_auto_model"
per_device_train_batch_size: 2
gradient_accumulation_steps: 8
num_train_epochs: 3
learning_rate: 2e-5
warmup_steps: 500
max_seq_length: 2048

# === LoRA ===
use_peft: true
lora:
  r: 16
  alpha: 32
  dropout: 0.1
  target_modules: ["q_proj", "v_proj", "k_proj", "o_proj"]  # Для современных моделей
  bias: "none"

# === КОМПОНЕНТЫ ===
freeze_vision_encoder: true
freeze_llm: false
train_projection_only: false

# === ОПТИМИЗАЦИЯ ===
bf16: true
dataloader_num_workers: 4
remove_unused_columns: false
generate_eval_examples: true
max_new_tokens: 256

# === СПЕЦИАЛЬНЫЕ ТОКЕНЫ ===
special_tokens:
  image_start: "<img>"
  image_end: "</img>"

# === ЛОГИРОВАНИЕ ===
logging_steps: 50
save_steps: 1000
eval_steps: 1000
report_to: "none"
run_name: "multimodal_auto_training" 